name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  unit_tests:
    name: Run Python unit tests
    runs-on: windows-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Start Azure Cosmos DB emulator
        run: |
          Write-Host "Launching Cosmos DB Emulator"
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator
      - name: Install test runner
        run: pip install pytest
      - name: Run Python tests
        run: pytest
